### ISSUE TITLE
toCP932ではなくてtoUTF8？

### ISSUE THREAD

**Issue by jiro4989** [callmekohei/myWindows2#1]
`man iconv`のドキュメントに記載あるのですが
`-f`は`--from`、`-t`は`--to`です。

```man
OPTIONS
       -f from-encoding, --from-code=from-encoding
              Use from-encoding for input characters.

       -t to-encoding, --to-code=to-encoding
              Use to-encoding for output characters.
```

UTF8に文字コード変換しているので
関数名は`toUTF8`のほうが適当かと思いました！

https://github.com/callmekohei/myWindows2/blob/afb5cd320776fedd2906091ca4c7dfb57d2ab6c0/.bashrc#L27-L31

**Comment by callmekohei** [comment]
おっしゃる通りです。。。
ありがとうございます！！！
